repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$
-   repo: local
    hooks:
    -   id: black
        name: black
        files: ".*.py"
        entry: poetry run black --config pyproject.toml
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        files: ".*.py"
        entry: poetry run isort --settings-path pyproject.toml
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: bandit
        name: bandit
        exclude: tests/*
        files: ".*.py"
        entry: poetry run bandit --configfile pyproject.toml
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        files: ".*.py"
        entry: poetry run flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        files: ".*.py"
        entry: poetry run mypy
        language: system
        types: [python]
