on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.vscode/**'
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

name: CI

env:
  POETRY_VERSION: "1.1.12"
  PYTHON_VERSION: "3.10"

jobs:
  static:
    name: Run static analysis tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/setup-python
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          poetry_version: ${{ env.POETRY_VERSION }}
      - name: Run linters
        run: nox -rs lint
      - name: Run formatters
        run: nox -rs format
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/setup-python
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          poetry_version: ${{ env.POETRY_VERSION }}
      - name: Run tests
        run: nox -rs test
      - name: Run coverage
        run: nox -rs coverage
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml